# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33dc1a567a82ff1930b71858cfa820658b5858c35c2fa7e94d222fefdfb5a34b57811774eda0780399df4afb1e90407bd7d88e71008352113f290d2d55e2d734

test:
  secret_key_base: 788812591e7cbaac7c73340785fc908d06cdf0cb91bfe32ab0589d72b647058561bd67dd40aee4a0fb3c1de6e7f8f5443a48666c7ff50581d76d1357e5a45ad2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
